stages:
  - "verify"
  - "doc"

.verify:
  image: "python:latest"
  variables:
    PYVER: "3.8"
  script:
    - "pip install --upgrade pip"
    - "pip install pipenv"
    - "pipenv --python $PYVER"
    - "pipenv install --dev"
    - "pipenv graph"
    - "pipenv run python setup.py test"
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch
        

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging

verify-2.7:
  extends: ".verify"
  stage: "verify"
  image: "python:2.7"
  variables:
    PYVER: "2.7"

verify-3.6:
  extends: ".verify"
  stage: "verify"
  image: "python:3.6"
  variables:
    PYVER: "3.6"
    
verify-3.7:
  extends: ".verify"
  stage: "verify"
  image: "python:3.7"
  variables:
    PYVER: "3.7"
        
verify-3.8:
  extends: ".verify"
  stage: "verify"
  image: "python:3.8"
  variables:
    PYVER: "3.8"
    
pages:
  stage: "doc"
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
