language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to run tests
script: nosetests --exe

#ensure pyyaml is there for testing
install:
  - pip install pyyaml

sudo: false
